package com.cjlu.backend

internal data class CatalogSeedRow(
    val id: String,
    val category: String,
    val titleEn: String,
    val titleZh: String,
    val descEn: String,
    val descZh: String,
    val turnaroundEn: String,
    val turnaroundZh: String,
    val checklistEn: List<String>,
    val checklistZh: List<String>,
    val isPopular: Boolean,
)

internal data class MessageSeedRow(
    val id: String,
    val category: String,
    val senderEn: String,
    val senderZh: String,
    val titleEn: String,
    val titleZh: String,
    val bodyEn: String,
    val bodyZh: String,
    val timeEn: String,
    val timeZh: String,
    val relatedServiceId: String?,
    val requiresAction: Boolean,
    val startsUnread: Boolean,
    val sentAtMillis: Long,
)

internal object ContentSeed {
    private val intlT = "3-5 working days" to "3-5 个工作日"
    private val acadT = "2-4 working days" to "2-4 个工作日"
    private val learnT = "Within 1 working day" to "1 个工作日内"
    private val campusT = "1-3 working days" to "1-3 个工作日"

    private val chkI = listOf(
        "Passport copy or current travel document" to "护照复印件或当前旅行证件",
        "Current visa or residence permit information" to "当前签证或居留许可信息",
        "Latest enrollment certificate or supporting proof" to "最新在读证明或相关材料",
    )
    private val chkA = listOf(
        "Student ID and basic personal details" to "学号和基础个人信息",
        "Reason for the request and supporting explanation" to "申请原因及相关说明",
        "Advisor or college confirmation if required" to "如需要，提供导师或学院确认",
    )
    private val chkL = listOf(
        "Current semester and course information" to "当前学期与课程信息",
        "Student identity details for verification" to "用于核验的学生身份信息",
        "Relevant academic record or target course details" to "相关成绩记录或目标课程信息",
    )
    private val chkC = listOf(
        "Dormitory or campus location information" to "宿舍或校园地点信息",
        "Contact phone number or preferred contact method" to "联系电话或偏好联系方式",
        "Clear issue description and preferred time if needed" to "清晰的问题描述及需要时段",
    )

    private fun c(
        id: String,
        category: String,
        titleEn: String,
        titleZh: String,
        descEn: String,
        descZh: String,
        time: Pair<String, String>,
        chk: List<Pair<String, String>>,
        popular: Boolean = false,
    ): CatalogSeedRow =
        CatalogSeedRow(
            id = id,
            category = category,
            titleEn = titleEn,
            titleZh = titleZh,
            descEn = descEn,
            descZh = descZh,
            turnaroundEn = time.first,
            turnaroundZh = time.second,
            checklistEn = chk.map { it.first },
            checklistZh = chk.map { it.second },
            isPopular = popular,
        )

    val catalogRows: List<CatalogSeedRow> = listOf(
        c("visa_extension", "International", "Visa Extension", "签证延期",
            "Visa and document extension support for international students.",
            "为国际学生提供签证及材料延期支持。", intlT, chkI, true),
        c("residence_permit", "International", "Residence Permit", "居留许可",
            "Manage residence permit guidance and progress.",
            "办理居留许可相关指引和进度。", intlT, chkI),
        c("back_to_cjlu", "International", "Back to CJLU", "返校申请",
            "Complete the return-to-campus submission flow.",
            "完成返校信息提交流程。", intlT, chkI),
        c("information_confirmation", "International", "Information Confirmation", "信息确认",
            "Confirm required personal or enrollment information.",
            "确认个人或学籍所需信息。", intlT, chkI),
        c("change_major", "Academic", "Change Major", "转专业",
            "Submit a request to adjust your current major pathway.",
            "提交当前专业调整申请。", acadT, chkA),
        c("ask_leave", "Academic", "Sick Leave", "病假申请",
            "Apply for sick leave so approved absences do not lower your attendance.",
            "因病无法上课时申请病假，审批通过后不影响出勤记录。", acadT, chkA, true),
        c("transfer_school", "Academic", "Transfer School", "转学",
            "Manage transfer-related academic paperwork.",
            "办理转学相关学籍材料。", acadT, chkA),
        c("quit_school", "Academic", "Quit School", "退学",
            "Start the official school withdrawal process.",
            "开始正式退学流程。", acadT, chkA),
        c("restudy", "Academic", "Restudy", "重修",
            "Arrange a restudy plan for a completed course.",
            "安排课程重修相关流程。", acadT, chkA),
        c("self_study", "Academic", "Self-study", "自修",
            "Register for self-study related academic approval.",
            "登记自修相关学业审批。", acadT, chkA),
        c("delay_exams", "Academic", "Delay Exams", "延考申请",
            "Apply to delay an exam due to approved reasons.",
            "因批准原因申请延考。", acadT, chkA),
        c("suspension_degree", "Academic", "Suspension of Degree", "休学",
            "Pause your current academic status through a formal request.",
            "通过正式申请暂停当前学业状态。", acadT, chkA),
        c("resume_school", "Academic", "Resume School", "复学",
            "Resume study after suspension or leave.",
            "在休学或请假后恢复在校学习。", acadT, chkA),
        c("school_calendar", "Learning", "School Calendar", "校历",
            "View semester dates, holidays, exams, and key deadlines.",
            "查看校历、假期、考试和关键时间节点。", learnT, chkL),
        c("scholarship", "Learning", "Scholarship", "奖学金",
            "Review scholarship information and application status.",
            "查看奖学金信息和申请状态。", learnT, chkL),
        c("class_schedule", "Learning", "Class Schedule", "课程表",
            "Open your timetable and classroom schedule.",
            "打开课程表和教室安排。", learnT, chkL, true),
        c("attendance_rate", "Learning", "Attendance Rate", "出勤率",
            "Track course attendance and participation records.",
            "查看课程出勤和参与记录。", learnT, chkL),
        c("transcripts", "Learning", "Transcripts", "成绩单",
            "View or request your academic transcript.",
            "查看或申请成绩单。", learnT, chkL),
        c("education_plan", "Learning", "Education Plan", "培养方案",
            "Check program requirements and course planning details.",
            "查看培养要求和课程规划信息。", learnT, chkL),
        c("changing_room", "Campus", "Changing Room", "换寝室",
            "Request a dormitory room change.",
            "提交宿舍换寝申请。", campusT, chkC),
        c("repair_request", "Campus", "Repair Request", "报修申请",
            "Report dormitory or campus facilities that need repair.",
            "报修宿舍或校园设施问题。", campusT, chkC, true),
        c("live_off_campus", "Campus", "Live Off Campus", "校外住宿",
            "Apply for approval to live outside campus housing.",
            "申请校外住宿审批。", campusT, chkC),
        c("room_card_key", "Campus", "Room Card / Key", "房卡和钥匙",
            "Handle room card or key support requests.",
            "处理房卡或钥匙相关支持申请。", campusT, chkC),
        c("bank_card_information", "Campus", "Bank Card Information", "银行卡信息",
            "Manage bank details for deposits and refund collection.",
            "管理押金和退款领取所需的银行卡信息。", campusT, chkC),
        c("deposit_refund", "Campus", "Deposit Refund", "押金退还",
            "Track dormitory or campus deposit refund requests.",
            "跟踪宿舍或校园押金退还申请。", campusT, chkC),
    )

    private val baseMsgTime = System.currentTimeMillis() - 3 * 24 * 60 * 60 * 1000L

    val messageRows: List<MessageSeedRow> = listOf(
        MessageSeedRow(
            id = "residence_permit_docs",
            category = "International",
            senderEn = "International Office",
            senderZh = "国际学生办公室",
            titleEn = "Residence permit document reminder",
            titleZh = "居留许可材料提醒",
            bodyEn = "Please prepare your passport, photo, and enrollment proof this week.",
            bodyZh = "请在本周内准备护照、照片和在读证明。",
            timeEn = "Today 09:20",
            timeZh = "今天 09:20",
            relatedServiceId = "residence_permit",
            requiresAction = true,
            startsUnread = true,
            sentAtMillis = baseMsgTime,
        ),
        MessageSeedRow(
            id = "repair_request_update",
            category = "Campus",
            senderEn = "Dormitory Management",
            senderZh = "宿舍管理中心",
            titleEn = "Repair request accepted",
            titleZh = "报修申请已受理",
            bodyEn = "Your dormitory air-conditioner repair has been assigned to maintenance staff.",
            bodyZh = "您的宿舍空调报修正在安排维修人员处理。",
            timeEn = "Yesterday 18:05",
            timeZh = "昨天 18:05",
            relatedServiceId = "repair_request",
            requiresAction = false,
            startsUnread = true,
            sentAtMillis = baseMsgTime + 60 * 60 * 1000L,
        ),
        MessageSeedRow(
            id = "classroom_update",
            category = "Academic",
            senderEn = "Academic Affairs Office",
            senderZh = "教务处",
            titleEn = "Classroom update for next week",
            titleZh = "课程表更新通知",
            bodyEn = "Some classroom locations will change next week. Please check your schedule.",
            bodyZh = "下周起部分课程教室有调整，请及时查看。",
            timeEn = "Tue 14:30",
            timeZh = "周二 14:30",
            relatedServiceId = "class_schedule",
            requiresAction = false,
            startsUnread = false,
            sentAtMillis = baseMsgTime + 2 * 60 * 60 * 1000L,
        ),
        MessageSeedRow(
            id = "return_campus_deadline",
            category = "International",
            senderEn = "International Office",
            senderZh = "国际学生办公室",
            titleEn = "Return-to-campus confirmation deadline",
            titleZh = "返校确认截止提醒",
            bodyEn = "Please complete your back-to-CJLU confirmation before Friday at 18:00 to avoid delays.",
            bodyZh = "请在周五 18:00 前完成返校确认，以免影响后续审核。",
            timeEn = "Today 11:10",
            timeZh = "今天 11:10",
            relatedServiceId = "back_to_cjlu",
            requiresAction = true,
            startsUnread = true,
            sentAtMillis = baseMsgTime + 3 * 60 * 60 * 1000L,
        ),
        MessageSeedRow(
            id = "attendance_follow_up",
            category = "Announcements",
            senderEn = "Student Success Team",
            senderZh = "学生发展服务团队",
            titleEn = "Attendance follow-up recommended",
            titleZh = "建议查看出勤记录",
            bodyEn = "Your attendance record needs a quick review this week. Open the attendance service to check the latest details.",
            bodyZh = "本周建议您尽快查看出勤情况，可通过出勤服务确认最新记录。",
            timeEn = "Mon 08:10",
            timeZh = "周一 08:10",
            relatedServiceId = "attendance_rate",
            requiresAction = true,
            startsUnread = false,
            sentAtMillis = baseMsgTime + 4 * 60 * 60 * 1000L,
        ),
    )
}
